[package]
name = "zsync-transport"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "SSH transport for zsync"

[dependencies]
color-eyre.workspace = true
tracing.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
bytes.workspace = true
uuid.workspace = true
zstd.workspace = true
tempfile.workspace = true

zsync-core = { path = "../core" }

[lints]
workspace = true
